footprint: [[-0.380, -0.240], [-0.380, 0.240], [0.110, 0.240], [0.11, -0.240]] #RIA-E100

obstacle_layer:
  observation_sources: scan point_cloud_sensor
  scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 6.0, raytrace_range: 10.0}
  track_unknown_space: true