base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: ria_base_controller/odom
  map_frame: map
     
  # Trajectory
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.03 # 10% of dt_ref is recommended
  min_samples: 10
  global_plan_overwrite_orientation: True # Overwrite orientation of local subgoals provided by the global planner
  global_plan_viapoint_sep: 0.5 
  max_global_plan_lookahead_dist: 5.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 5
  publish_feedback: false
  shrink_horizon_backup: true
  allow_init_with_backwards_motion: false
  exact_arc_length: false
  shrink_horizon_min_duration: 10.0

  # Robot     
  max_vel_x: 0.5
  max_vel_x_backwards: 0.15
  max_vel_y: 0 
  max_vel_theta: 1.0
  acc_lim_x: 0.01
  acc_lim_y: 0 
  acc_lim_theta: 0.5
  min_turning_radius: 0.0
  wheelbase: 0.0 # The distance between the rear axle and the front axle
  cmd_angle_instead_rotvel: false

  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    vertices: [[-0.380, -0.240], [-0.380, 0.240], [0.110, 0.240], [0.11, -0.240]]
 
  # GoalTolerance
  xy_goal_tolerance: 0.35 # Allowed final euclidean distance to the goal position in meters
  yaw_goal_tolerance: 0.8 # Allowed final orientation error in radians
  free_goal_vel: false # Remove the goal velocity constraint such that the robot can arrive at the goal with maximum speed
     
  # Obstacles
  min_obstacle_dist: 0.1 # This value must also include our robot radius, since footprint_model is set to "point"
  include_costmap_obstacles: true 
  costmap_obstacles_behind_robot_dist: 1.0 # Limit the occupied local costmap obstacles taken into account for planning behind the robot 
  obstacle_poses_affected: 30 
  inflation_dist: 0.0
  include_dynamic_obstacles: false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5.0

  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0
 
  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 1.0
  weight_max_vel_y: 0.0
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_y: 0.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1000.0 # Optimization weight for forcing the robot to choose only forward directions
  weight_kinematics_turning_radius: 1.0 # Optimization weight for enforcing a minimum turning radius (only for carlike robots)
  weight_optimaltime: 10.0
  weight_obstacle: 50.0
  weight_viapoint: 1.0
  weight_inflation: 0.1
  weight_dynamic_obstacle: 10 # not in use yet
  weight_adapt_factor: 2.0
 
  # Homotopy Class Planner
  enable_homotopy_class_planning: false
  simple_exploration: false
  enable_multithreading: false
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false 

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false